### ISSUE TITLE
😯

### ISSUE THREAD

**Issue by aashutoshrathi** [amany9000/Sahara#13]
https://github.com/amany9000/Sahara/blob/1fd34c739f2f171088ecaf1860199e76c76c97bc/app/src/components/Pages/AboutUs/AboutUs.js#L14

This line :heart:

**Comment by DivyeshPuri** [comment]
@DipanshKhandelwal Dipansh has a kind heart.

**Comment by DipanshKhandelwal** [comment]
@DivyeshPuri @aashutoshrathi :heart:
